flask_app/app/products/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint,make_response,session
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt,bootstrap
import ast,random,string
from flask_session import Session
from app.models import User, Product

 #, send_reset_emai
products= Blueprint('products',__name__)

@products.route("/item/<int:id>")
def item(id):
    product = Product.query.get_or_404(id)
    reviews = ast.literal_eval(product.reviews)
    tags = ast.literal_eval(product.tags)
    list = []
    items = Product.query.all()
    for item in items:

        if tags[0] in item.tags:
            list.append(item)
        else:

            pass
    random.shuffle(list)
    list= list[:3]

    return render_template('products/products.html',product = product,reviews=reviews,list = list)


@products.route("/wishlist/<int:id>",methods = ['POST','GET'])
@login_required
def wishlist(id):
    page = request.args.get('page')

    user = current_user
    product = Product.query.get_or_404(id)
    wishlist = user.wishlist
    wishlist = wishlist +' '+ (str(id))
    user.wishlist = wishlist
    db.session.commit()
    print(user.wishlist)

    if page:
        return redirect(page)
    return redirect(url_for('main.home'))

    # return render_template('main/base.html')

@products.route('/wishlist/items/',methods = ['POST','GET'])
@login_required
def wishlist_items():
    user = current_user
    wishlist = user.wishlist
    wishlist = list(map(int,wishlist.split()))
    wishlist = list(set(wishlist))
    wishlist = Product.query.filter(Product.id.in_(wishlist)).all()
    return render_template('products/wishlist.html',wishlist=wishlist)

@products.route('/add_to_cart/<int:id>/',methods = ['POST','GET'])
@login_required
def add_to_cart(id):
    page = request.args.get('page')
    if session.get("cart"):
        cart = session.get('cart')
        # print(cart)
        session["cart"] = cart + ' ' +str(id)
    else:
        session["cart"] = str(id)
    if page:
        return redirect(page)
    return redirect(url_for('main.home'))


@products.route('/cart/',methods = ['POST','GET'])
@login_required
def cart():
    cart = session.get('cart')
    # print(cart)
    user = current_user
    if cart:
        cart = list(map(int,cart.split()))
        cart = list(set(cart))
        cart = Product.query.filter(Product.id.in_(cart)).all()
    else:
        pass
    return render_template('products/cart.html',cart=cart)

@products.route('/remove_from_cart/<int:id>/',methods = ['POST','GET'])
@login_required
def remove_from_cart(id):
    cart = session.get('cart')
    print(cart)
    # user = current_user
    if cart:
        cart = list(map(int,cart.split()))
        cart = list(set(cart))


        cart.remove(id)
        cart = ' '.join(map(str,cart))
        session["cart"] = cart


    else:
        pass
    return redirect(url_for('main.home'))

flask_app/app/templates/products/cart.html
{% extends "main/base.html" %}
{{ bootstrap.load_css() }}
{{ bootstrap.load_js() }}
{% block content %}
<script type="text/javascript">
  function removeFromCart(productId) {

    fetch(`remove_from_cart/${productId}`,
    {method: 'POST'}
  )
  }
</script>

      <div class="album py-5 bg-light">
        <div class="container">

          <nav aria-label="breadcrumb ">
            <ol class="breadcrumb ">
              <li class="breadcrumb-item"><a href="{{url_for('main.home')}}">
                Home
              </a>
            </li>
              <li class="breadcrumb-item active" aria-current = 'page'>Cart 🛒</li>
            </ol>
          </nav>

          <div class= "mt-5 row">
        {% if cart %}
      {% for item in cart %}
      <div class="col-md-4">
        <div class="card  bg-light mb-4 shadow-sm">
          <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> -->
          <img src="{{item['thumbnail']}}" class="bd-placeholder-img card-img-top" width="100%" height="150" alt="...">
          <div class="card-body" style="height:180px">
            <h5 class="card-title">{{item['title']}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">${{item['price']}}</h6>
            <p class="card-text"></p>


            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-primary m-2" onclick="removeFromCart({{item['id']}})"><a class="text-white">Remove from cart</a></button>

                <button type="button" class="btn btn-sm btn-secondary m-2"><a href="{{url_for('products.item',id= item['id'] )}}" class="text-white">View</a></button>
              </div>
              <small class="text-muted"></small>
            </div>
          </div>
        </div>
      </div>
      {% endfor  %}
      {% else %}
      <h2>Cart is empty</h2>
      {% endif %}


      </div>
      </div>
      </div>
      <div class="mx-auto">
        <button type="button" class="btn btn-sm btn-primary m-2"><a class="text-white" href="#">Check out</a></button>
      </div>

{% endblock content %}

flask_app/app/templates/products/products.html
{% extends "main/base.html" %}
{{ bootstrap.load_css() }}
{{ bootstrap.load_js() }}
{% block content %}
<script>
function addToWishList(productId) {
  // fetch(`http://127.0.0.1:5000/wishlist/${productId}`,
  fetch(`/wishlist/${productId}`,

  {method: 'POST'}

)
  window.alert('Added to cart 🛒')
}


function addToCart(productId) {
  // fetch(`http://127.0.0.1:5000/add_to_cart/${productId}`,
    fetch(`/add_to_cart/${productId}`,
  {method: 'POST'}

)
// window.alert('Added to cart 🛒')
}

</script>


</header>

<!-- content -->
<section class="py-5">
  <div class="container">
    <nav aria-label="breadcrumb ">
      <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="{{url_for('main.home')}}">
          Home
        </a>
      </li>
        <li class="breadcrumb-item active" aria-current = 'page'>{{product['title']}}</li>
      </ol>
    </nav>
    <div class="row gx-5">
      <aside class="col-lg-6">
        <div class="border rounded-4 mb-3 d-flex justify-content-center">
          <a data-fslightbox="mygalley" class="rounded-4" target="_blank" data-type="image" href="">
            <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit" src="{{product['thumbnail']}}" />
          </a>
        </div>

        <!-- thumbs-wrap.// -->
        <!-- gallery-wrap .end// -->
      </aside>
      <main class="col-lg-6">
        <div class="ps-lg-3">
          <h4 class="title text-dark">
            {{product['title']}}
          </h4>
          <div class="d-flex flex-row my-3">
            <div class="text-warning mb-1 me-2">
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fas fa-star-half-alt"></i>
              <span class="ms-1">
                {{product['ratings']}} stars
              </span>
            </div>
            <br>
            <span class="text-muted"><i class="fas fa-shopping-basket fa-sm mx-1"></i>{{  product['stock']}}</span>
            <span class="text-success ms-2"> . In stock</span>
          </div>

          <div class="mb-3">
            <span class="h5">${{product['price']}}</span>
            <!-- <span class="text-muted">/per box</span> -->
          </div>

          <!-- <p>
          {{product['description']}}
          </p> -->

          <div class="row">


            <dt class="col-3">Rating</dt>
            <dd class="col-9">  {{product['ratings']}} </dd>

            {% if product['brand'] %}

            <dt class="col-3">Brand</dt>
            <dd class="col-9">{{product['brand']}}</dd>

            {% endif %}
            <!-- <br> -->
            <hr/>

          </div>

          <div class="row mb-4">
          </div>

          <a href="#" class="btn btn-warning shadow-0"> Buy now </a>
          <button type="button" class="btn btn-primary shadow-0" name="button"  onclick="" >
      <i class="me-1 fa fa-shopping-basket"></i> <a href="{{url_for('products.add_to_cart', id =product['id'],page=request.url)}}" class="text-white">
        Add to cart
      </a>
      </button>
      <button type="button" class="btn btn-light border border-secondary py-2 icon-hover px-3" name="button"  onclick="" >
  <i class="me-1 fa fa-shopping-basket"></i>
  <a href="{{url_for('products.wishlist', id =product['id'],page=request.url)}}" class="text-dark">
    Save
  </a>
  </button>

        </div>
      </main>
    </div>
  </div>
</section>
<!-- content -->

<section class="bg-light border-top py-4">
  <div class="container">
    <div class="row gx-4">
      <div class="col-lg-8 mb-4">
        <div class="border rounded-2 px-3 py-2 bg-white">
          <!-- Pills navs -->

          <!-- Pills navs -->

          <!-- Pills content -->
          <div class="tab-content" id="ex1-content">
            <div class="tab-pane fade show active" id="ex1-pills-1" role="tabpanel" aria-labelledby="ex1-tab-1">

              <table class="table border mt-3 mb-2">
                <tr>
                  <th class="py-2">Return Policy:</th>
                  <td class="py-2">{{product['shippingInformation']}}</td>
                </tr>
                <tr>
                  <th class="py-2">Shipping Info:</th>
                  <td class="py-2">  {{product['returnPolicy']}}  </td>
                </tr>

              </table>
            </div>
          </div>
          <!-- Pills content -->
        </div>

        <div class="album py-5 bg-light">
          <div class="container">

            <div class="row">

        {% for product in list %}
        <div class="col-md-4">
          <div class="card  bg-light mb-4 shadow-sm">
            <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> -->
            <img src="{{product['thumbnail']}}" class="bd-placeholder-img card-img-top" width="100%" alt="...">
            <div class="card-body" style="height:180px">
              <h5 class="card-title">{{product['title']}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">${{product['price']}}</h6>
              <p class="card-text"></p>


              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" onclick="" class="btn btn-sm btn-primary m-2"><a class="text-white" href="{{url_for('products.add_to_cart', id =product['id'],page=request.url)}}">Add to cart</a></button>

                  <button type="button" class="btn btn-sm btn-secondary m-2"><a href="{{url_for('products.item',id= product['id'] )}}" class="text-white">View</a></button>
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
        {% endfor  %}
      </div>
    </div>
  </div>
      </div>


        <div class=" bg-white col-lg-4">
          <h2 class=""> Reviews</h2>
          {% for item in reviews %}

          <div class="card bg-light m-3 shadow-sm" >
            <div class="card-body">
              <h5 class="card-title">{{item['reviewerName']}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{item['reviewerEmail'] }}</h6>
              <p class="card-text">{{item['comment']}}</p>
              <p class="card-text"> Rated this {{item['rating']}}</p>

            </div>
          </div>


          {% endfor %}


        </div>
      </div>
    </div>

</section>


{% endblock content %}

flask_app/app/templates/products/wishlist.html
{% extends "main/base.html" %}
{{ bootstrap.load_css() }}
{{ bootstrap.load_js() }}

{% block content %}
<script type="text/javascript">
  function addToCart(productId) {
    // fetch(`http://127.0.0.1:5000/add_to_cart/${productId}`,
    fetch(`/add_to_cart/${productId}/`,
    {method: 'POST'}

    )
    // window.alert('Added to cart 🛒')
  }

</script>


        <div class="album py-5 bg-light">
          <div class="container">

            <nav aria-label="breadcrumb ">
              <ol class="breadcrumb ">
                <li class="breadcrumb-item"><a href="{{url_for('main.home')}}">
                  Home
                </a>
              </li>
                <li class="breadcrumb-item active" aria-current = 'page'>Wishlist</li>
              </ol>
            </nav>

            <div class= "mt-5 row">

        {% for item in wishlist %}
        <div class="col-md-4">
          <div class="card  bg-light mb-4 shadow-sm">
            <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> -->
            <img src="{{item['thumbnail']}}" class="bd-placeholder-img card-img-top" width="100%"  alt="...">
            <div class="card-body" style="height:180px">
              <h5 class="card-title">{{item['title']}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">${{item['price']}}</h6>
              <p class="card-text"></p>


              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-primary m-2" onclick="addToCart({{item['id']}})"><a class="text-white" href="{{url_for('products.add_to_cart',id = item['id'],page=request.url)}}">Add to cart</a></button>

                  <button type="button" class="btn btn-sm btn-secondary m-2"><a href="{{url_for('products.item',id= item['id'] )}}" class="text-white">View</a></button>
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
        {% endfor  %}
      </div>
    </div>
  </div>


{% endblock content %}