flask_app/app/users/forms.py
from flask_wtf import csrf,FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField,EmailField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from app.models import User


class RegistrationForm(FlaskForm):
    firstname = StringField('First Name',
                                validators = [DataRequired(),Length(min=2,max =20)])
    lastname = StringField('Last Name',
                                validators = [DataRequired(),Length(min=2,max =20)])
    email = EmailField('Email',
                                validators = [DataRequired()])
    password = PasswordField('Password' ,validators = [DataRequired()] )
    # confirm_password = PasswordField('Confirm Password',validators = [DataRequired(),EqualTo('password')] )

    submit = SubmitField('Sign Up')

    def validate_username(self,username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('This user name has been taken Please choose another')

    def validate_email(self,email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('This email has been taken Please choose another')

class LoginForm(FlaskForm):

    email = EmailField('Email',
                                validators = [DataRequired()])
    password = PasswordField('Password' ,validators = [DataRequired()] )

    remember = BooleanField('Remember Me',default ='checked')
    submit = SubmitField('Login')




class UpdateAccountForm(FlaskForm):
    firstname = StringField('First Name',
                                validators = [DataRequired(),Length(min=2,max =20)])
    lastname = StringField('Last Name',
                                validators = [DataRequired(),Length(min=2,max =20)])
    email = EmailField('Email',
                                validators = [DataRequired()])
    picture = FileField('Update Profile Picture',validators = [FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

    def validate_username(self,username):
        if username.data != current_user.username:

            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('This user name has been taken Please choose another')


    def validate_email(self,email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('This email has been taken Please choose another')

class RequestResetForm(FlaskForm):
    email = EmailField('Email',
                                validators = [DataRequired()])
    submit = SubmitField('Submit')
    def validate_email(self,email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('Email doesn exist')

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password' ,validators = [DataRequired()] )
    confirm_password = PasswordField('Confirm Password',validators = [DataRequired(),EqualTo('password')] )
    submit = SubmitField('Reset')

flask_app/app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt,bootstrap

from app.models import User#, Post
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from app.users.utils import save_pic #, send_reset_emai
users= Blueprint('users',__name__)

@users.route('/signup',methods = ['POST','GET'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(firstname=form.firstname.data,lastname=form.lastname.data,email=form.email.data,password=hashed_password,wishlist='')

        db.session.add(user)
        db.session.commit()
        flash(f'Welcome {form.firstname.data}',category='success')
        return redirect(url_for('users.login'))
    return render_template('users/signup.html', title = 'Register',form = form)

@users.route('/login',methods = ['POST','GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    print('hiiii')
    if form.validate_on_submit():
        print('nnnnnnnnnnnnn')
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember = form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful',category='danger')

    print('dddddddddd')
    return render_template('users/login.html', title = 'Login',form = form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account',methods = ['POST','GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.picture.data:
        print(current_user.image_file)
        picture_file = save_pic(form.picture.data)
        current_user.image_file = picture_file
    if form.validate_on_submit():
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.email = form.email.data
        db.session.commit()
        flash('your account has been updated')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
        form.email.data = current_user.email
    image_file = url_for('static',filename='profile_pics/' + current_user.image_file)
    print(image_file)
    return render_template('users/account.html',title='Account',
                                        image_file = image_file,form = form)

@users.route("/user/<username>")
# @login_required
def user_posts(username):
    page = request.args.get('page',1,type = int)
    user = User.query.filter_by(username=username).first_or_404()
    # posts = Post.query.paginate(page=page ,per_page = 10)
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page ,per_page = 3)

    return render_template('user_posts.html',posts=posts,user=user)

#
#
# @users.route("/reset_request",methods=['GET', 'POST'])
# def reset_request():
#     if current_user.is_authenticated:
#         return redirect(url_for('main.home'))
#     form = RequestResetForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         send_reset_email(user)
#
#         flash('An email has been sent to reset your password')
#         return redirect(url_for('users.login'))
#     return render_template('reset_request.html', title='Reset Password', form=form)
#
# @users.route('/reset_password/<token>',methods=['GET', 'POST'])
# def reset_token(token):
#
#     if current_user.is_authenticated:
#         return redirect(url_for('main.home'))
#     user = User.verify_reset_token(token)
#     if user is None :
#         flash('Token hsa expired','warning')
#         return redirect(url_for('users.reset_request'))
#     form = ResetPasswordForm()
#     if form.validate_on_submit():
#         hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
#         user.password=hashed_password
#         db.session.commit()
#         flash(f'Your pass word has been updated')
#         return redirect(url_for('users.login'))
#     return render_template('reset_token.html', title='Reset Password', form=form)

flask_app/app/templates/users/account.html
{% extends "main/base.html" %}
{{ bootstrap.load_css() }}
{{ bootstrap.load_js() }}
{% block content %}
<div class="w-100 justify-content-center ">
  <div class="card   mb-3">
    <div class="card-body">
      <h1 class=" text-center ">Profile</h1>

    </div>
  </div>

<div class="w-100 d-flex justify-content-center ">

<div class="card  mb-3 w-50">


  <div class="card-body">
    <!-- <h5 class="card-title">{{ current_user.username }}</h5>
    <p class="card-text">{{ current_user.email }}</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
    <form class="" action="" method="post" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      {% with messages = get_flashed_messages(with_categories = true)%}
        {% if messages %}
          {% for category,message in messages %}
          <p class="alert alert-success">{{ message }}</p>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <fieldset class="">
        <legend>Account Info</legend>

        <div class="m-3">


            {{ form.firstname.label }}<br>
            {% if form.firstname.errors %}
                  <!-- {{ form.firstname }} -->
                  {% for error in form.firstname.errors  %}
                    <span class="alert alert-danger p-1">{{ error }}</span>
                  {% endfor %}
            {% endif %}
            <div class="input-group mb-3">
              <!-- <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
              {{ form.firstname(class='border-0 border-bottom border-dark w-50') }}
              <div class="input-group-append">
                <span class="input-group-text p-2 " id="basic-addon2"><svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" stroke-width="2" d="M7 19H5a1 1 0 0 1-1-1v-1a3 3 0 0 1 3-3h1m4-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm7.441 1.559a1.907 1.907 0 0 1 0 2.698l-6.069 6.069L10 19l.674-3.372 6.07-6.07a1.907 1.907 0 0 1 2.697 0Z"/>
          </svg>
          </span>
              </div>
            </div>
        </div>

        <div class="m-3">


            {{ form.lastname.label }}<br>
            {% if form.lastname.errors %}
                  <!-- {{ form.lastname }} -->
                  {% for error in form.lastname.errors  %}
                    <span class="alert alert-danger p-1">{{ error }}</span>
                  {% endfor %}
            {% endif %}
            <div class="input-group mb-3">
              <!-- <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
              {{ form.lastname(class='border-0 border-bottom border-dark w-50') }}
              <div class="input-group-append">
                <span class="input-group-text p-2 " id="basic-addon2"><svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" stroke-width="2" d="M7 19H5a1 1 0 0 1-1-1v-1a3 3 0 0 1 3-3h1m4-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm7.441 1.559a1.907 1.907 0 0 1 0 2.698l-6.069 6.069L10 19l.674-3.372 6.07-6.07a1.907 1.907 0 0 1 2.697 0Z"/>
          </svg>
          </span>
              </div>
            </div>
        </div>

        <div class="m-3">
            {{ form.email.label }}<br>
            {% if form.email.errors %}
                  <!-- {{ form.email }} -->
                  {% for error in form.email.errors  %}
                    <span  class="alert alert-danger p-1">{{ error }}</span>
                  {% endfor %}
            {% endif %}
            <div class="input-group mb-3">
              <!-- <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
              {{ form.email(class='border-0 border-bottom border-dark w-50') }}
              <div class="input-group-append">
                <span class="input-group-text p-2  " id="basic-addon2"><svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
  <path stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" stroke-width="2" d="M7 19H5a1 1 0 0 1-1-1v-1a3 3 0 0 1 3-3h1m4-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm7.441 1.559a1.907 1.907 0 0 1 0 2.698l-6.069 6.069L10 19l.674-3.372 6.07-6.07a1.907 1.907 0 0 1 2.697 0Z"/>
</svg>
</span>
              </div>
            </div>
                  </div>

        <br>
        <div class="input-group mb-3">
          <div class="input-group-prepend">

          </div>
          


      </fieldset>
      <div class="d-flex justify-content-center w-100">

        {{ form.submit(class="btn btn-dark w-50 m-3")}}
      </div>
    </form>
  </div>
  </div>
</div>
</div>




{% endblock content %}

flask_app/app/templates/users/login.html
{% extends "main/base.html" %}
{{ bootstrap.load_css() }}
{{ bootstrap.load_js() }}
{% block content %}
    <div class="d-flex align-items-center justify-content-center vh-100">
    <form method="post" action="{{url_for('users.login')}}"  style="width:400px" class="  border  border-2 border-dark-subtle rounded p-5">
      {{ form.hidden_tag() }}
      {{form.csrf_token}}
   <div class="mb-3">
          {% with messages = get_flashed_messages(with_categories = True) %}
          {% if messages %}
           {% for category, message in messages %}
             <span class="alert alert-{{category}}  p-1">{{message}}</span>
          {% endfor %}
          {% endif%}
          {% endwith %}
          <br>

     {{ form.email.label(class = "form-label")}}

     {% if form.email.errors %}
      {% for error in form.email.errors %}
        <span class="text-danger">{{error}}</span>
      {% endfor %}
     {% endif %}
     {{ form.email(class = "form-control",placeholder='Enter username' ) }}

   </div>
   <div class="mb-3">

     {{ form.password.label(class = "form-label")}}

     {{ form.password(class = "form-control",placeholder='Enter password' ) }}
   </div>
   <div class="mb-3 form-check">

     {{ form.remember(class='form-check-input-dark')}}
     {{ form.remember.label}}

     <a href="#" class="link-secondary">  Forgot password?</a>
   </div>
   <div class="w-100 p-2 justify-content-center d-flex">

     {{ form.submit(class="btn btn-dark w-50")}}
   </div>
   <p>Dont have an account? <a href="{{url_for('users.signup')}}">Sign up</a> </p>
  </form>
</div>

{% endblock content %}

flask_app/app/templates/users/signup.html
{% extends "main/base.html" %}
{{ bootstrap.load_css() }}
{{ bootstrap.load_js() }}
{% block content %}


    <div class="d-flex align-items-center justify-content-center vh-100">

    <form method="post"  action="{{url_for('users.signup')}}" class="border  border-2 border-dark-subtle rounded p-5 " style="width:400px">
      {{ form.hidden_tag() }}
        {{form.csrf_token}}
      {% with messages = get_flashed_messages(with_categories = True) %}
      {% if messages %}
       {% for category,message in messages %}
         <span class="alert alert-{{category}} p-1">{{message}}</span>
      {% endfor %}
      {% endif%}
      {% endwith %}

      <div class="mb-3">

             {{ form.firstname.label(class = "form-label")}}

             {% if form.firstname.errors %}
              {% for error in form.firstname.errors %}
                <span class="text-danger">{{error}}</span>
              {% endfor %}
             {% endif %}
             {{ form.firstname(class = "form-control ml-2",placeholder='Enter your firstname' ) }}
      </div>

      <div class="mb-3">

             {{ form.lastname.label(class = "form-label")}}

             {% if form.lastname.errors %}
              {% for error in form.lastname.errors %}
                <span class="text-danger">{{error}}</span>
              {% endfor %}
             {% endif %}
             {{ form.lastname(class = "form-control ml-2",placeholder='Enter your lastname' ) }}
      </div>

   <div class="mb-3">


          {{ form.email.label(class = "form-label")}}

          {% if form.email.errors %}
           {% for error in form.email.errors %}
             <span class="text-danger">{{error}}</span>
           {% endfor %}
          {% endif %}
          {{ form.email(class = "form-control",placeholder='Enter email' ) }}
   </div>



   <div class="mb-3">

     {{ form.password.label(class = "form-label")}}
     {{ form.password(class = "form-control",placeholder='Enter password' ) }}

   </div>



   <div class="w-100 p-2 justify-content-center d-flex">

       {{ form.submit(class="btn btn-dark w-50")  | safe}}
   </div>
   <p>Already have an account? <a href="{{url_for('users.login')}}">Login</a> </p>
  </form>
</div>
{% endblock content %}