flask_app/app/posts/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    content= TextAreaField('Content',validators=[DataRequired()])
    submit = SubmitField('Post')

flask_app/app/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from app import db
# from app.models import Post
from app.posts.forms import PostForm

posts = Blueprint('posts',__name__)

@posts.route('/post/new',methods = ['POST','GET'])
@login_required
def new_post():
    form= PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,content = form.content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post created')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',form=form,legend = 'New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html',title = post.title,post = post)

@posts.route("/post/<int:post_id>/update",methods = ['POST','GET'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form= PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('your post has been updated')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method =='GET':

        form.title.data = post.title
        form.content.data = post.content

    return render_template('create_post.html',title='Update Post',form=form,legend = 'Update Post')

@posts.route("/post/<int:post_id>/delete",methods = ['POST','GET'])
@login_required
def delete(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('main.home'))

flask_app/app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt,bootstrap

from app.models import User#, Post
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from app.users.utils import save_pic #, send_reset_emai
users= Blueprint('users',__name__)

@users.route('/signup',methods = ['POST','GET'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(firstname=form.firstname.data,lastname=form.lastname.data,email=form.email.data,password=hashed_password,wishlist='')

        db.session.add(user)
        db.session.commit()
        flash(f'Welcome {form.firstname.data}',category='success')
        return redirect(url_for('users.login'))
    return render_template('users/signup.html', title = 'Register',form = form)

@users.route('/login',methods = ['POST','GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    print('hiiii')
    if form.validate_on_submit():
        print('nnnnnnnnnnnnn')
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember = form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful',category='danger')

    print('dddddddddd')
    return render_template('users/login.html', title = 'Login',form = form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account',methods = ['POST','GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.picture.data:
        print(current_user.image_file)
        picture_file = save_pic(form.picture.data)
        current_user.image_file = picture_file
    if form.validate_on_submit():
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.email = form.email.data
        db.session.commit()
        flash('your account has been updated')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
        form.email.data = current_user.email
    image_file = url_for('static',filename='profile_pics/' + current_user.image_file)
    print(image_file)
    return render_template('users/account.html',title='Account',
                                        image_file = image_file,form = form)

@users.route("/user/<username>")
# @login_required
def user_posts(username):
    page = request.args.get('page',1,type = int)
    user = User.query.filter_by(username=username).first_or_404()
    # posts = Post.query.paginate(page=page ,per_page = 10)
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page ,per_page = 3)

    return render_template('user_posts.html',posts=posts,user=user)

#
#
# @users.route("/reset_request",methods=['GET', 'POST'])
# def reset_request():
#     if current_user.is_authenticated:
#         return redirect(url_for('main.home'))
#     form = RequestResetForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         send_reset_email(user)
#
#         flash('An email has been sent to reset your password')
#         return redirect(url_for('users.login'))
#     return render_template('reset_request.html', title='Reset Password', form=form)
#
# @users.route('/reset_password/<token>',methods=['GET', 'POST'])
# def reset_token(token):
#
#     if current_user.is_authenticated:
#         return redirect(url_for('main.home'))
#     user = User.verify_reset_token(token)
#     if user is None :
#         flash('Token hsa expired','warning')
#         return redirect(url_for('users.reset_request'))
#     form = ResetPasswordForm()
#     if form.validate_on_submit():
#         hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
#         user.password=hashed_password
#         db.session.commit()
#         flash(f'Your pass word has been updated')
#         return redirect(url_for('users.login'))
#     return render_template('reset_token.html', title='Reset Password', form=form)

flask_app/app/templates/about.html
{% extends "base.html" %}
{% block content %}
  <h1>About Page</h1>
{% endblock content %}

flask_app/app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% if title %}
      <title>Flask Blog - {{ title }}</title>
    {% else %}
      <title>Flask Blog</title>
    {% endif %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class=" w-100 ">

<div class="row g-0 ">
      {% if current_user.is_authenticated %}
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-dark vh-100 sticky-top border-right border-primary " style="width: 280px;">

    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <!-- <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg> -->
      <span class="fs-4">Flask Blog</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        {% if request.path == url_for('main.home') %}
          <a class="nav-link active" href="{{ url_for('main.home')}}" aria-current="page">
          <!-- <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg> -->
          Home
        </a>
        {% else %}
          <a class="nav-link text-white" href="{{ url_for('main.home')}}" aria-current="page">
            Home
          </a>
        {% endif %}
      </li>
      <li>
        {% if request.path == url_for('posts.new_post') %}
        <a href="{{ url_for('posts.new_post')}}" class="nav-link active">
          <!-- <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg> -->
          New Post
        </a>
        {% else %}
            <a href="{{ url_for('posts.new_post')}}" class="nav-link text-white">New Post  </a>
        {% endif %}
      </li>
      <li>
        {% if request.path == url_for('users.account') %}
        <a href="{{ url_for('users.account')}}" class="nav-link active">
          <!-- <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg> -->
            Profile
        </a>
        {% else %}
        <a href="{{ url_for('users.account')}}" class="nav-link text-white">
          <!-- <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg> -->
            Profile
        </a>
        {% endif %}
      </li>
      <li>

        <a href="#" class="nav-link text-white">
          <!-- <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg> -->
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <!-- <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg> -->
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="{{ url_for('static',filename ='profile_pics/'+current_user.image_file )}}" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>{{current_user.username}}</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" style="">
        <li><a class="dropdown-item" href="{{ url_for('users.logout')}}">Sign out</a></li>
      </ul>
    </div>
  </div>
    {% endif %}
<div class="col  w-100 justify-content-center bg-dark">


    {% block content %}
    {% endblock %}
  </div>

  </div>
</div>


  </body>

</html>

flask_app/app/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class=" d-flex justify-content-center bg-dark h-100">
  {% with messages = get_flashed_messages(with_categories = true)%}
    {% if messages %}
      {% for category,message in messages %}
      <p>{{ message }}</p>
      {% endfor %}
    {% endif %}
  {% endwith %}

<div class="w-100 justify-content-center " style="margin-top: 8rem;margin-left: 10rem;">

  <form class="" action="" method="post">
    {{ form.hidden_tag() }}
    <div class="card text-white bg-dark mb-3" style="max-width: 40rem;">
      <div class="card-header">{{legend}}</div>

      <div class="card-body">

        {{ form.title.label }}<br>
        {% if form.title.errors %}
              {{ form.title }}
              {% for errors in form.title.errors  %}
                <span>{{ error }}</span>
              {% endfor %}
        {% endif %}
        {{ form.title(class='bg-dark border text-white rounded w-50') }}
      </div>
      <div class="card-body">
          {{ form.content.label }}<br>
          {% if form.content.errors %}
                {{ form.content }}
                {% for errors in form.content.errors  %}
                  <span>{{ error }}</span>
                {% endfor %}
          {% endif %}
          {{ form.content(class='bg-dark border text-white rounded w-50') }}
      </div>
      <div class="d-flex justify-content-center">

      {{ form.submit(class='btn btn-primary w-50')}}
    </div>
    </div>


  </form>
</div>


</div>
{% endblock content %}

flask_app/app/templates/home.html
{% extends "base.html" %}
{% block content %}
{% with messages = get_flashed_messages(with_categories = true)%}
  {% if messages %}
    {% for category,message in messages %}
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="justify-content-center bg-dark " >
  <div class="card  text-white bg-dark mb-3">
  <div class="card-body">
    <h1 class="text-white text-center ">Posts</h1>

  </div>
</div>
  {% for post in posts.items %}
  <div class="d-flex  justify-content-center w-100">

    <div class="card text-white bg-dark mb-md-5 w-50 ">
      <div class="card-header">
        <img class="" style="
          width: 30px;
          height: 30px;
          border-radius: 30px;
        "   src="{{ url_for('static',filename ='profile_pics/'+post.author.image_file )}}" alt="Hi">
        <a href="{{ url_for('posts.post',post_id=post.id)}}">{{ post.title}}</a>
      </div>
      <div class="card-body">
        <span class="card-title h5"> {{ post.content}} </span>
        <br>

<hr>
        <a href="{{ url_for('users.user_posts',username = post.author.username)}}">{{post.author.username }}</a>
      </div>
    </div>
  </div>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=1) %}
      {% if page_num %}
        {% if posts.page == page_num%}
          <a class="btn btn-info mb-4 " href="{{ url_for('main.home',page=page_num)}}">{{page_num}} </a>
        {% else %}
          <a class="btn btn-outline-info mb-4 " href="{{ url_for('main.home',page=page_num)}}">{{page_num}} </a>

        {% endif %}
      {% else %}
        <span class="text-white">...</span>
      {% endif %}

    {% endfor %}

  </div>

{% endblock content %}

flask_app/app/templates/post.html
{% extends "base.html" %}

{% block content %}

<div class="d-flex w-100 h-100 justify-content-center align-items-center">


<div class="card text-white bg-dark w-75">
<div class="card-header">
    <img height="25" width="25" src="{{ url_for('static',filename ='profile_pics/'+post.author.image_file )}}" alt="Hi"> {{post.author.username }}
</div>
<div class="card-body">
  <h5 class="card-title">{{ post.title}}</h5>
  <p class="card-text">{{ post.content}} </p>
  <p class="card-subtitle"> {{ post.date_posted.strftime('%Y-%m-%d') }}</p>

</div>
{% if post.author == current_user %}
<div class="card-footer text-muted">

  <a href="{{url_for('posts.update_post',post_id=post.id)}}" class="btn btn-primary mr-3">Edit </a><span>  .   .</span> <a class="btn btn-danger" href="{{url_for('posts.delete',post_id=post.id)}}">Delete</a>

</div>
{% endif %}
</div>
</div>




{% endblock content %}

flask_app/app/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
        <div class="card-dark text-white border border-secondary p-3 rounded mt-4" style='width:300px;margin-left:400px'>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control bg-light form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control bg-light form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group" onclick="sendMail() ">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_app/app/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
    <div class="card-dark text-white border border-secondary p-3 rounded mt-4" style='width:300px;margin-left:400px'>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control bg-light form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control bg-light form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control bg-light form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control bg-light form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_app/app/templates/user_posts.html
{% extends "base.html" %}
{% block content %}



<div class="justify-content-center bg-dark " >
  <div class="card  text-white bg-dark mb-3">
  <div class="card-body">
    <h1 class="text-white mb3">Post by {{ user.username }} ({{posts.total}})</h1>


  </div>
</div>
  {% for post in posts.items %}
  <div class="d-flex  justify-content-center w-100">

    <div class="card text-white bg-dark mb-md-5 w-50 ">
      <div class="card-header">
        <img class="" style="
          width: 30px;
          height: 30px;
          border-radius: 30px;
        "   src="{{ url_for('static',filename ='profile_pics/'+post.author.image_file )}}" alt="Hi">
        <a href="{{ url_for('posts.post',post_id=post.id)}}">{{ post.title}}</a>
      </div>
      <div class="card-body">
        <span class="card-title h5"> {{ post.content}} </span>
        <br>

<hr>
        <a href="{{ url_for('posts.user_posts',username = post.author.username)}}" >{{post.author.username }}</a>
      </div>
    </div>
  </div>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=1) %}
      {% if page_num %}
        {% if posts.page == page_num%}
          <a class="btn btn-info mb-4 " href="{{ url_for('posts.user_posts',username=user.username,page=page_num)}}">{{page_num}} </a>
        {% else %}
          <a class="btn btn-outline-info mb-4 " href="{{ url_for('posts.user_posts',username=user.username,page=page_num)}}">{{page_num}} </a>

        {% endif %}
      {% else %}
        <span class="text-white">...</span>
      {% endif %}

    {% endfor %}

  </div>

{% endblock content %}