flask_app/app/main/routes.py
from flask import render_template, request, Blueprint
from app.models import Product
from app import db,bootstrap
from flask_login import login_required
main = Blueprint('main',__name__)


@main.route('/')
@main.route('/home')
# @login_required
def home():
    # products = Product.query.all()

    page = request.args.get('page',1,type = int)
    # posts = Post.query.paginate(page=page ,per_page = 10)
    products = Product.query.paginate(page=page ,per_page = 12)

    return render_template('main/home.html',products=products)

@main.route('/about')
def about():
    return render_template('about.html', title = 'About')

flask_app/app/products/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint,make_response,session
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt,bootstrap
import ast,random,string
from flask_session import Session
from app.models import User, Product

 #, send_reset_emai
products= Blueprint('products',__name__)

@products.route("/item/<int:id>")
def item(id):
    product = Product.query.get_or_404(id)
    reviews = ast.literal_eval(product.reviews)
    tags = ast.literal_eval(product.tags)
    list = []
    items = Product.query.all()
    for item in items:

        if tags[0] in item.tags:
            list.append(item)
        else:

            pass
    random.shuffle(list)
    list= list[:3]

    return render_template('products/products.html',product = product,reviews=reviews,list = list)


@products.route("/wishlist/<int:id>",methods = ['POST','GET'])
@login_required
def wishlist(id):
    page = request.args.get('page')

    user = current_user
    product = Product.query.get_or_404(id)
    wishlist = user.wishlist
    wishlist = wishlist +' '+ (str(id))
    user.wishlist = wishlist
    db.session.commit()
    print(user.wishlist)

    if page:
        return redirect(page)
    return redirect(url_for('main.home'))

    # return render_template('main/base.html')

@products.route('/wishlist/items/',methods = ['POST','GET'])
@login_required
def wishlist_items():
    user = current_user
    wishlist = user.wishlist
    wishlist = list(map(int,wishlist.split()))
    wishlist = list(set(wishlist))
    wishlist = Product.query.filter(Product.id.in_(wishlist)).all()
    return render_template('products/wishlist.html',wishlist=wishlist)

@products.route('/add_to_cart/<int:id>/',methods = ['POST','GET'])
@login_required
def add_to_cart(id):
    page = request.args.get('page')
    if session.get("cart"):
        cart = session.get('cart')
        # print(cart)
        session["cart"] = cart + ' ' +str(id)
    else:
        session["cart"] = str(id)
    if page:
        return redirect(page)
    return redirect(url_for('main.home'))


@products.route('/cart/',methods = ['POST','GET'])
@login_required
def cart():
    cart = session.get('cart')
    # print(cart)
    user = current_user
    if cart:
        cart = list(map(int,cart.split()))
        cart = list(set(cart))
        cart = Product.query.filter(Product.id.in_(cart)).all()
    else:
        pass
    return render_template('products/cart.html',cart=cart)

@products.route('/remove_from_cart/<int:id>/',methods = ['POST','GET'])
@login_required
def remove_from_cart(id):
    cart = session.get('cart')
    print(cart)
    # user = current_user
    if cart:
        cart = list(map(int,cart.split()))
        cart = list(set(cart))


        cart.remove(id)
        cart = ' '.join(map(str,cart))
        session["cart"] = cart


    else:
        pass
    return redirect(url_for('main.home'))

flask_app/app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt,bootstrap

from app.models import User#, Post
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from app.users.utils import save_pic #, send_reset_emai
users= Blueprint('users',__name__)

@users.route('/signup',methods = ['POST','GET'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(firstname=form.firstname.data,lastname=form.lastname.data,email=form.email.data,password=hashed_password,wishlist='')

        db.session.add(user)
        db.session.commit()
        flash(f'Welcome {form.firstname.data}',category='success')
        return redirect(url_for('users.login'))
    return render_template('users/signup.html', title = 'Register',form = form)

@users.route('/login',methods = ['POST','GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    print('hiiii')
    if form.validate_on_submit():
        print('nnnnnnnnnnnnn')
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember = form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful',category='danger')

    print('dddddddddd')
    return render_template('users/login.html', title = 'Login',form = form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account',methods = ['POST','GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.picture.data:
        print(current_user.image_file)
        picture_file = save_pic(form.picture.data)
        current_user.image_file = picture_file
    if form.validate_on_submit():
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.email = form.email.data
        db.session.commit()
        flash('your account has been updated')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
        form.email.data = current_user.email
    image_file = url_for('static',filename='profile_pics/' + current_user.image_file)
    print(image_file)
    return render_template('users/account.html',title='Account',
                                        image_file = image_file,form = form)

@users.route("/user/<username>")
# @login_required
def user_posts(username):
    page = request.args.get('page',1,type = int)
    user = User.query.filter_by(username=username).first_or_404()
    # posts = Post.query.paginate(page=page ,per_page = 10)
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page ,per_page = 3)

    return render_template('user_posts.html',posts=posts,user=user)

#
#
# @users.route("/reset_request",methods=['GET', 'POST'])
# def reset_request():
#     if current_user.is_authenticated:
#         return redirect(url_for('main.home'))
#     form = RequestResetForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         send_reset_email(user)
#
#         flash('An email has been sent to reset your password')
#         return redirect(url_for('users.login'))
#     return render_template('reset_request.html', title='Reset Password', form=form)
#
# @users.route('/reset_password/<token>',methods=['GET', 'POST'])
# def reset_token(token):
#
#     if current_user.is_authenticated:
#         return redirect(url_for('main.home'))
#     user = User.verify_reset_token(token)
#     if user is None :
#         flash('Token hsa expired','warning')
#         return redirect(url_for('users.reset_request'))
#     form = ResetPasswordForm()
#     if form.validate_on_submit():
#         hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
#         user.password=hashed_password
#         db.session.commit()
#         flash(f'Your pass word has been updated')
#         return redirect(url_for('users.login'))
#     return render_template('reset_token.html', title='Reset Password', form=form)

flask_app/app/templates/main/base.html
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Ecommerce Project </title>
        <!-- Favicon-->

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand " href="{{url_for('main.home')}}">Shopify</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{{url_for('main.home')}}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{{url_for('products.wishlist_items')}}">Wishlist</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="d-flex justify-content-end w-100">

                    <form class="d-flex ms-4 end-0">
                      {% if current_user.is_authenticated %}
                        <button class="btn " type="submit">
                          <a class="text-decoration-none text-dark fw-bolder " href="{{url_for('products.cart')}}">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <!-- <span class="badge bg-dark text-white ms-1 rounded-pill">0</span> -->
                          </a>
                        </button>
                      {% endif %}

                      {% if current_user.is_authenticated %}

                    <div class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle text-decoration-none text-dark" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{current_user.firstname}}</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{{url_for('users.account')}}">My account</a></li>
                            <!-- <li><a class="dropdown-item" href="#!">Popular Items</a></li> -->
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="{{url_for('users.logout')}}">Log Out</a></li>
                        </ul>
                    </div>
                    {% else %}
                      <button class="btn btn-outline-dark p-0" type="submit">
                        <a class="nav-link " href="{{url_for('users.login')}}">Sign in</a>
                      </button>
                    {% endif %}
                  </form>

                </div>



                </div>
            </div>
        </nav>
        <!-- Header-->

        <!-- Section-->

        {% block content %}

        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>


    </body>
</html>

flask_app/app/templates/main/home.html
{% extends "main/base.html" %}
{{ bootstrap.load_css() }}
{{ bootstrap.load_js() }}
{% block content %}
<script type="text/javascript">
  function addToCart(productId) {
    // fetch(`http://127.0.0.1:5000/add_to_cart/${productId}`,
      fetch(`/add_to_cart/${productId}`,
    {method: 'POST'}

  )
  window.alert('Added to cart 🛒')
  }

</script>
<main role="main">


        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Shop in style</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Lorem ipsum type shii</p>
                </div>
            </div>
        </header>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">

        {% for product in products.items %}
        <div class="col-md-3">
          <div class="card  bg-light mb-4 shadow-sm">
            <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> -->
            <img src="{{product['thumbnail']}}"  class="bd-placeholder-img bg-light card-img-top" width="100%"  alt="...">
            <div class="card-body" style="height:180px">
              <h5 class="card-title">{{product['title']}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">${{product['price']}}</h6>
              <p class="card-text"></p>


              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-primary m-2" onclick=""><a class="text-white" href="{{url_for('products.add_to_cart',id = product['id'],page=request.url)}}">Add to cart</a></button>

                  <button type="button" class="btn btn-sm btn-secondary m-2"><a href="{{url_for('products.item',id= product['id'] )}}" class="text-white">View</a></button>
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
        {% endfor  %}









      </div>
    </div>
  </div>
  <br>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if products.page==1 %}
      <li class="page-item disabled">
        {% else %}
            <li class="page-item">
        {% endif %}
        <a  href="{{ url_for('main.home',page=products.page+1)}}" class="page-link">Previous</a>
      </li>
      {% for page_num in products.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=1) %}
      {% if page_num %}
      {% if products.page == page_num%}
      <li class="page-item active" aria-current="page">
        <a  class="page-link" href="{{ url_for('main.home',page=page_num)}}">

          {{page_num}}
          <span class="sr-only">(current)</span>
        </a>
      </li>

      {% else %}

      <li class="page-item"><a class="page-link" href="{{ url_for('main.home',page=page_num)}}">{{page_num}}</a></li>
      {% endif %}
      {% else %}
      <li class="page-item"><a class="page-link" href="#">...</a></li>
      {% endif %}

      {% endfor %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('main.home',page=products.page+1)}}">Next</a>
      </li>
    </ul>

  </nav>

</main>


{% endblock content %}